#!/bin/sh


#wir haengen nur die Bridge in bat0, da batman nur begrenzte Mengen an Interfaces vertraegt.
/sbin/brctl addbr wireguard
/sbin/ip link set dev wireguard up
/usr/local/sbin/batctl if add  wireguard
#/usr/sbin/brctl addif br-ffintern bat0          # und hängen das bat0 interface auf die Bridge, da es im interface bereich nicht funktioniert
/sbin/ip route add 10.80.0.0/16 dev bat0 table freifunk

#Port isolation bridge
ebtables --append FORWARD --logical-in wireguard --jump DROP

batctl it 5000
batctl gw_mode server 300MBit/300MBit
batctl bl 1                     #Bridge loop detection aktivieren

