#!/bin/bash
        /etc/init.d/openvpn stop
        sed '/remote/d' /etc/openvpn/vpnac.conf > /tmp/output.conf
        LOCATION="de"
        server=$( wget -q  https://vpn.ac/status -O - | grep -E -o '>[^.]+\.vpn\.ac<' | tr -d '[<>]' | grep "${LOCATION}") # Only check selected country
        fhostname=$(netselect -s 1 -t 5 ${server} | awk '{print $2}')  # Pipes each of the servers into Netselect und selects fastest
        #echo $fhostname
        IPs=$(host $fhostname | awk '{print $4}')
        #echo $IPs
        FinalIP=$(netselect  -s 1 -t 5  $IPs | awk '{print $2}')
        #echo ${FinalIP}
        echo "remote $FinalIP 50000 # $fhostname" >> /tmp/output.conf
        rm /etc/openvpn/vpnac.conf
        mv /tmp/output.conf /etc/openvpn/vpnac.conf
        /etc/init.d/openvpn start
