---

- name: install net-tools
  package:
    name: net-tools
    state: latest
- name: install unattended-upgrades
  package:
    name: unattended-upgrades
    state: latest
- name: use 90-ansible-unattended-upgrades config file for unattended-upgrades
  copy:
    src: "etc/apt/apt.conf.d/90-ansible-unattended-upgrades"
    dest: "/etc/apt/apt.conf.d/90-ansible-unattended-upgrades"
    owner: root
    group: root
    mode: 0644
- name: install mlocate
  package:
    name: mlocate
    state: latest
- name: install vim
  package:
    name: vim
    state: latest
