---
# tasks file for wireguard

# Add specified repository into sources list using specified filename.
#- name: Add wireguard repository to system
#  apt_repository:
#    repo: deb http://deb.debian.org/debian/ unstable main
#    state: present
#    filename: wireguard
#
#- name: Add pinning for the repository
#  copy:
#    dest: /etc/apt/preferences.d/limit-unstable
#    content: |
#      Package: *
#      Pin: release a=unstable
#      Pin-Priority: 90

#- name: Update repositories on hosts
#  apt:
#    update_cache: yes

- name: install net-tools
  package:
    name: net-tools
    state: latest
- name: install unattended-upgrades
  package:
    name: unattended-upgrades
    state: latest
- name: use 90-ansible-unattended-upgrades config file for unattended-upgrades
  copy:
    src: "etc/apt/apt.conf.d/90-ansible-unattended-upgrades"
    dest: "/etc/apt/apt.conf.d/90-ansible-unattended-upgrades"
    owner: root
    group: root
    mode: 0644
- name: install mlocate
  package:
    name: mlocate
    state: latest
